version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
